---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(ggplot2)
library(lubridate)   
library(hydroGOF)
library(xtable)
library(knitr)
library(tidyr)
library(RSQLite)
library(agricolae)
library(scales)
library(zoo)

```
# ### load obs data
###filter out FD5 and seedling crop 
```{r}
upDir <- "D:/R/CombinedData/"
obsData <- "D:/R/CombinedData/"

obsFD <- read.table(paste0(obsData, "FallDtreatment.txt"),
                   header = TRUE)
obsFDFL<- obsFD %>%
  dplyr::filter(FD!="FD5")%>%
  dplyr::filter(Water!="dry")%>%
  mutate(StartDate=dmy(StartDate),MidDate=dmy(MidDate),FinishDate=dmy(FinishDate),Clock.Today=dmy(Clock.Today))%>%
  mutate(GrowthSeason1=as.factor(paste0("Gs_",GrowthSeason))) %>% # creating more intuitive labels here
  mutate(Rotation1=as.factor(paste0("Rt_",Rotation))) %>%
  mutate(ExpUnitCode=as.factor(paste0(Name,GrowthSeason1,Rotation1))) %>%
  mutate(Clock.Today1 = as.POSIXct(paste(Clock.Today,Time),format="%Y-%m-%d %H:%M:%S"))%>%
  mutate(GrowthSeason2=as.factor(paste0("Y",GrowthSeason,"(",Period,")"))) %>%
 mutate(Rotation2=as.factor(paste0("R",Rotation)))%>%
  dplyr::filter(Variable=="Fraction"|Variable=="LAI")
obsFDFL
```
###load Tt data
```{r}
upDir <- "D:/R/"
obsData <- "D:/R/TtAll/"

Tt<- read.table(paste0(obsData, "df.all.txt"),
               header = TRUE)
TtA <- Tt %>% mutate(Clock.Today=dmy(Clock.Today), ExpUnitCode=as.factor(ExpName))%>%
  dplyr::filter(Tbb==1)


obsFDFLT <-merge(obsFDFL,TtA,by=c("Clock.Today","ExpUnitCode","Water","Defoliation","SowingDate","FD","Experiment")) %>%
  mutate(GrowthRotation=as.factor(paste0(GrowthSeason.x,Rotation.x)))
  summary(obsFDFLT)
  obsFDFLT
  
```
###my theme
```{r}
mytheme1<-theme(
     panel.spacing=unit(.01, "lines"),
     panel.border = element_rect(colour = "black",size=1), 
     panel.grid.major = element_blank(),
     panel.grid.minor = element_blank(),
     axis.line = element_line(colour = "black",size = 1),
     axis.text.x = element_text(face = "plain", color = "black", size = 14,angle=90, vjust=0.5, hjust = 1),
     axis.text.y = element_text(face = "plain", color = "black", size = 14),
     axis.title.x=element_text(face="bold",colour="black",size = 14),
     axis.title.y=element_text(face="bold",colour="black",size = 14),
     strip.background = element_rect(colour = "black", fill = "white",size=1),
     strip.text.x = element_text(size=14, angle=0, face = "plain"), 
     strip.text.y = element_text(size=14, face="plain"),
     legend.title = element_text(colour="black", size=14, face="bold"),
     axis.text = element_text(face = "bold", vjust = 0.5, size = 14))

mytheme3<-theme(
     legend.title = element_text(colour="black", size=14, face="bold"),
     legend.text = element_text(colour="black", size = 14,face="plain"),
     panel.spacing=unit(.01, "lines"),
     panel.border = element_rect(colour = "black",size=1), 
     panel.grid.major = element_blank(),
     panel.grid.minor = element_blank(),
     axis.line = element_line(colour = "black",size = 1),
     axis.text.x = element_text(face = "plain", color = "black", size = 14, vjust=0.5, hjust = 1),
     axis.text.y = element_text(face = "plain", color = "black", size = 14),
     axis.title.x=element_text(face="bold",colour="black",size = 14),
     axis.title.y=element_text(face="bold",colour="black",size = 14),
     strip.background = element_rect(colour = "black", fill = "white",size=1),
     strip.text.x = element_text(size=14, angle=0, face = "plain"), 
     strip.text.y = element_text(size=14, face="plain"),
     axis.text = element_text(face = "bold", vjust = 0.5, size = 14),
    legend.position = "right", legend.box = "vertical")
```

###LAI and PAR
```{r,fig.height=4, fig.width=8}
obsFDFLT.data<-obsFDFLT%>%
  unique()%>%
  dplyr::select(Clock.Today,ExpUnitCode,Name,Collection,GrowthSeason.x,Rotation.x,StartDate,MidDate,FinishDate,Interval,Variable,VariableUnits,Time,Observed,StdDEV,GrowthRotation,ID,ExperimentID)

obsFDFLTLAI <- obsFDFLT.data%>%
  dplyr::filter(Variable=="LAI")
obsFDFLTF <- obsFDFLT.data%>%
  dplyr::filter(Variable=="Fraction")
  
ObsFDLF<-merge(obsFDFLTLAI,obsFDFLTF,by=c("Clock.Today","ExpUnitCode","Name","Collection","GrowthSeason.x","Rotation.x","StartDate","MidDate","FinishDate","Interval","Time","GrowthRotation","ID","ExperimentID"))

phyll <- "D:\\R\\"
StartGrazing <- read.table(paste0(phyll, "ExperimentList.txt"), 
                      header = TRUE)
StartGrazing1<-StartGrazing %>%
  mutate(GrowthRotation= as.factor(paste0(GrowthSeason,Rotation)))
ObsFDLF1<- merge(StartGrazing1,ObsFDLF,by=c("Name","Collection","GrowthRotation"))%>%
   filter(Interval<=50)
 # dplyr::filter(Name!="Iversen_121DefoliationHHFDFD5"|GrowthSeason.x!="4")%>%
 #  dplyr::filter(Name!="Iversen_121DefoliationLSFDFD5"|GrowthRotation!="14")%>%
 #   dplyr::filter(Name!="Iversen_121DefoliationHHFDFD5"|Rotation.x!="2")%>%
 # dplyr::filter(Name!="Iversen_121DefoliationSSFDFD5"|GrowthSeason.x!="4")%>%
 #  dplyr::filter(Name!="Iversen_121DefoliationSSFDFD5"|GrowthRotation!="26")%>%
 #  dplyr::filter(Name!="Iversen_121DefoliationSSFDFD5"|GrowthRotation!="22")%>%
 #  dplyr::filter(Name!="Iversen_121DefoliationSSFDFD5"|GrowthRotation!="23")%>%
 #  dplyr::filter(Name!="Iversen_121DefoliationSSFDFD5"|GrowthRotation!="13")%>%
 #   dplyr::filter(Name!="Iversen_121DefoliationSSFDFD5"|GrowthRotation!="38")%>%
 #  dplyr::filter(Name!="Iversen_121DefoliationSSFDFD5"|GrowthRotation!="31")

test1 <- function(x) {1-exp(-0.81*x)}
stat_function(fun = test1)
 
ObsFDLF1%>%
  #filter(ExperimentID=="E3")%>%
  ggplot(aes(x=Observed.x,y=Observed.y,shape=ID))+theme_bw()+ylab("Franctional radiation interception")+xlab(bquote(bold('LAI ('*m^2~m^-2*')')))+
  geom_point(size=2)+theme(legend.title = element_blank())+
   geom_segment(aes(x = 3.6, y = 0, xend = 3.6, yend = 0.95))+
  #geom_segment(aes(x = 0, y = 0.95, xend = 3.45, yend = 0.95))+
  geom_segment(aes(x = 4.25, y = 0.2, xend = 3.6, yend = 0),
                  arrow = arrow(length = unit(0.5, "cm")))+
  #facet_wrap(~Stage,ncol = 2)+
  stat_function(fun = test1,color="black",size=1)+
  theme(axis.title.x=element_text(face="bold",colour="black",size = 12))+
 theme(axis.title.y=element_text(face="bold",colour="black",size = 12))+mytheme3+
 annotate("text", x=1.5, y=1, size = 5, label ="paste(y == 1-exp(-0.81*x),~~R^2==0.93 )", parse=T)+
  annotate("text", x=4.5, y=0.25, size = 5, label ="paste(LAIcrit==3.6)", parse=T)
  ggsave("D:/R/Pictures/C6/PAR/PAR.png", width=8, height=5  , dpi=500) 
```
#### Extinction_coef evaluation
```{r,fig.height=4, fig.width=8}
library(plyr)
Exc.K<-ObsFDLF1%>%
  mutate(Fra=1-Observed.y)%>%
  mutate(lnFI=log(Fra))
  
  #filter(ExperimentID=="E3")

lm_eqn3 <- function(Exc.K){
  m <- lm(lnFI~Observed.x, Exc.K);
  eq <- substitute(italic(y) == Observed.x + lnFI %.% italic(Observed.x)*","~~italic(R)^2~"="~r2, 
                   list(Observed.x = format(coef(m)[1], digits = 2), 
                       lnFI = format(coef(m)[2], digits = 2), 
                        r2 = format(summary(m)$r.squared, digits = 3)))
  as.character(as.expression(eq));                 
}


eqs3 <- ddply(Exc.K,.(Stage),lm_eqn3)


Exc.K%>%
  ggplot(aes(x=Observed.x,y=lnFI,color=ID,label=GrowthRotation,shape=Stage))+geom_text()+theme_bw()+ylab("ln (I/IO)")+xlab(bquote(bold('LAI ('*m^2~m^-2*')')))+
  #geom_point(size=2)+
   geom_smooth(method = "lm", se = TRUE,linetype=1 , colour="black")+
  #facet_wrap(~Stage,ncol = 2)+
  mytheme3+
  geom_text(data = eqs3, aes(y =0, x = 3.5, label = V1), 
          color = 'black',  parse = TRUE)+
  theme(axis.title.x=element_text(face="bold",colour="black",size = 12))+
 theme(axis.title.y=element_text(face="bold",colour="black",size = 12))
  detach(package:plyr)
```
###PAR and acculmated PARi
##PAR

```{r}
TtA1<-TtA%>%
  dplyr::filter(Tbb==1)%>%
  dplyr::select(radn,Clock.Today,ExpUnitCode,GrowthSeason,Rotation)
  
obsFDF<-obsFDFL%>%
  dplyr::filter(Variable=="Fraction")%>%
  dplyr::select(Clock.Today, Name, Collection,ID,Variable,VariableUnits, Observed,StdDEV, ExpUnitCode,StartDate,MidDate,FinishDate)

ObsPARFD.Raw <-merge(obsFDF,TtA1,by=c("ExpUnitCode"))%>%
  mutate(fPAR=as.factor(ifelse(Clock.Today.x==Clock.Today.y,Observed,"NA")))%>%
  mutate(fPAR=as.factor(ifelse(Clock.Today.y==StartDate,0.1,paste0(fPAR))))%>%
  mutate(StdDEV1=as.factor(ifelse(Clock.Today.x==Clock.Today.y,StdDEV,"NA")))%>%
  dplyr::select(-Clock.Today.x,-Observed,-StdDEV)%>%
  unique()
write.csv(ObsPARFD.Raw,"D:/R/ObsPARFD.Raw.csv", row.names = FALSE)

```
###fPAR interpolate for each rotation

```{r}
upDir <- "D:/R/"
obsData <- "D:/R/"

ObsPARFD.Raw1<- read.table(paste0(obsData, "ObsPARFD.Raw.txt"),
               header = TRUE)%>%
  unique()

UniExp <- unique(ObsPARFD.Raw1$ExpUnitCode)

fPARFD.df <- data.frame()
  
for(i in 1:length(UniExp))
{
  
  ObsfPARFD<-ObsPARFD.Raw1%>%
   filter(ExpUnitCode==UniExp[i])%>%
  mutate(Clock.Today=dmy(Clock.Today.y))
  
 
 fPARFD.data<-ObsfPARFD%>%
  mutate(fPAR1=approx(Clock.Today, fPAR, xout =Clock.Today, 
         method="linear", 
         rule = 2)$y)##interpolate function 
  

 fPARFD.df<- rbind( fPARFD.df, fPARFD.data)

}

summary(fPARFD.df)
fPARFD.df
write.csv(fPARFD.df,"D:/R/fPARFD.df.csv", row.names = FALSE)
```

###Accumlated PAR for every rotation
```{r}

UniExp <- unique(fPARFD.df$ExpUnitCode)

PARiFD.df <- data.frame()
  
for(i in 1:length(UniExp))
{
  
  ObsPARiFD<-fPARFD.df%>%
    
   filter(ExpUnitCode==UniExp[i])%>%
     mutate(PARi=radn*fPAR1)%>% 
   dplyr::select(-fPAR,-StdDEV1)%>%
    unique()
  
 
 PARiFD.data<-ObsPARiFD%>%
  mutate( PARi.sum = cumsum(PARi))##accmulated function
  

 PARiFD.df<- rbind( PARiFD.df, PARiFD.data)

}

summary(PARiFD.df)
PARiFD.df
write.csv(PARiFD.df,"D:/R/PARiFD.df.csv", row.names = FALSE)
```
###calculated RUE value
####Join yield and PARi table together
```{r}
PARiFD.df1<-PARiFD.df%>%
  mutate(Clock.Today=dmy(Clock.Today.y))%>%
  dplyr::select(ExpUnitCode,Name,Clock.Today,fPAR1,PARi,PARi.sum,GrowthSeason,Rotation)

# obsTDM<-ObsL.Raw%>%
#   mutate(GrowthRotation=as.factor(paste0(GrowthSeason.x,Rotation.x)))%>%
#   dplyr::filter(Water.x=="irr")%>%
#   dplyr::filter(Defoliation.x=="LL")%>%
#   dplyr::filter(FD.x=="FD5")%>%
#   dplyr::filter(Tb==1)%>%
#   dplyr::filter(Variable=="shootbiomass"|Variable=="RootWt")
# 
#   
# RUE.RAW<-merge(obsTDM,PARi.df1,by=c("Clock.Today","Name","ExpUnitCode"))
```
###check the intepolate function
```{r,fig.height=5, fig.width=8}
PARiFD.df2<-PARiFD.df1%>%
  dplyr::filter(Name=="Iversen_121DefoliationSSFDFD2")
  
PARiFD.df2%>%
  ggplot(aes(x=Clock.Today, y=fPAR1))+geom_point(size=2)+theme_bw()+xlab("Date")+ylab("Fractional intercepted radiation")+
  #geom_smooth(method = "lm", se = TRUE,linetype=1 , colour="black")+
 facet_grid(GrowthSeason~Rotation)+
  theme(axis.title.x=element_text(face="bold",colour="black",size = 12))+
 theme(axis.title.y=element_text(face="bold",colour="black",size = 12))

```




















