---
title: "R Notebook"
output: html_notebook
---

```{r Load, warning=FALSE, fig.height=8, fig.width=8}
# install.packages("zoo")
library(dplyr)
library(ggplot2)
library(lubridate)   
library(hydroGOF)
library(xtable)
library(knitr)
library(tidyr)
library(RSQLite)
library(agricolae)
library(scales)
library(zoo)
```

```{r}
upDir <- "D:/R/"
obsData <- "D:/R/"
ExpList<- read.table(paste0(obsData, "ExperimentList.txt"),
                       header = TRUE)
ExpList
```
```{r}
Exp<-ExpList%>%
  mutate(ExpUnitCode=paste0(Experiment,Water,Defoliation,SowingDate,FD,GrowthSeason,Rotation))%>%
  unique()
  
Exp
#unique(Exp)

```
```{r}
Met <- "D:/R/"
MetD<- "D:/R/"
MetLincoln<- read.table(paste0(MetD,"Lincolnmet.txt"),
                       header = TRUE)
MetL<-MetLincoln%>%
  mutate(Clock.Today=dmy(Clock.Today))
MetL

```
```{r}
# You can have all Thermal-time functions and ...
# Tt function by parameter combination (this can also be done by loop)

# Tt calc method 1
ttBaby <- function(tn,tx){
  
  # test if Tn is < Tx 
  ta <- (tn+tx)*0.5
  
  tb <-0
  
  return(ta-tb)
  
}

ttBaby(10,20)

```
# we_beta function 
```{r}

  we_beta <- function(tav, t_min, t_opt, t_max, t_ref = t_opt) {  

   # tav <- maxt_weight * maxt + (1 - maxt_weight) * mint
   
    res <- ifelse ((tav > t_min) & (tav < t_max),
    {
        a <- log(2.0) / log((t_max - t_min) / (t_opt - t_min))
        
        refeff <- t_opt * (2 * ((tav - t_min)^a) * ((t_opt - t_min)^a) -
                               ((tav - t_min) ^ (2 * a))) / ((t_opt - t_min) ^ (2 * a))
        
        a <- log(2.0) / log((t_max - t_min) / (t_opt - t_min))
        
        refefft <- t_opt * (2 * ((t_ref - t_min)^a) * ((t_opt - t_min)^a) -
                                ((t_ref - t_min) ^ (2 * a))) / ((t_opt - t_min) ^ (2 * a))
        refeff / refefft
    }, 0)

    return (res)
}

```
### calculate TTWE
##Tb=1:5 for loop

```{r}
TTfunc <- function(Tmin ,Tmax){         
 
  if (Tmin>Tmax){
   print("Tmin>Tmax")
   break
  } 
  
  Topt <- 30
  TTav() <- df(i)
  TTsum() <- df()
  
  for(n in 1:8){ 
    
  tn <- 0
    
    TT_tn <-0
    
    tn <- ((0.931 +  0.114*n - 0.0703 * n^2
            + 0.0053 * n^3) * (Tmax-Tmin)) + Tmin # 8-h temperature
    
    for(Tb in 1:5){
    
    
    TT_tn(i) <- we_beta(tn,Tb,30,40) * tn # beta-fun parameters are hardcoded here ... these can/should be externalised
    
    TTsum(i) <- max(TT_tn(i),0) + TTsum(i)
    
    }
  TTav(i) <- TTsum(i)/8
  
  return(TTav(i))
  }}

TTfunc(1,2)

```



##broken stick function
```{r}
tt_card <- data.frame(temp=c(1.0,  5.0,  10,  15,  30,  40),
                      TT=c(0.0,  3.0,  6.5, 10,  25,  0.0))
# Create and test interpolation function 

temp_ref  <- 25 # x-axes reference
temp <- tt_card$temp # x-axes
TT <- tt_card$TT # y-axes


int_func <- function(temp,TT,temp_ref){

# if temp is too low or too high give extreme TT values
 if(temp_ref>temp[length(temp)]) {
   
   out <- TT[length(TT)] 
   
 } else if (temp_ref<temp[1]) {
   
   out <- TT[1]
   
 } else {
   
# else interpolate
   
   tryCatch(  
   
  out <- approx(temp, TT, xout = temp_ref, 
         method="linear", 
         rule = 2)$y,
  error = function(e) 
  {
  out <- NA
  }
) 
  
} # end if check

  return(out)  
  
 }
  
int_func(temp,TT,temp_ref)

```

#create REF Jones CA, Ritchie JT, Kiniry JR, Godwin DC (1986) Subroutine structure.In 'CERES-Maize: A simulation model of maize growth anddevelopment'. (Eds CA Jones, JR Kiniry) pp. 49-194. (Texas A&M University Press: Texas, USA

```{r}

TTfunc <- function(Tmin ,Tmax){         
 
  if (Tmin>Tmax){
   print("Tmin>Tmax")
   break
 } 
  
  TTav  <- 0
  TTsum <- 0
  
  for(n in 1:8){ 
    
    tn <- 0
    
    TT_tn <- 0
    
    tn <- ((0.931 +  0.114*n - 0.0703 * n^2
            + 0.0053 * n^3) * (Tmax-Tmin)) + 
      Tmin # 8-h temperature
    
    TT_tn <- int_func(tt_card$temp, tt_card$T,tn) 
    
    TTsum <- max(TT_tn,0) + TTsum
    
 #   print(TT_tn)
    
    }
  TTav <- TTsum/8
  
  return(TTav)
  }

TTfunc(10,30)

```

##XXXXX
```{r}

UniExp<-unique(Exp$ExpUnitCode)

df.all <- data.frame()

for(i in 1 : length(Exp$ExpUnitCode))
{
  
 Exp.sub<- Exp %>%
    filter(ExpUnitCode==UniExp[i])
  
 StDate<-dmy(Exp.sub$StartDate)
 EndDate<-dmy(Exp.sub$FinishDate)
  
Met.sub<-MetL%>%
  filter(between(Clock.Today,StDate,EndDate))

tt.df <- Met.sub %>% #rowwise()%>%
                 mutate(ExpName=Exp.sub$Name, Tt = ttBaby(mint,maxt))%>%
                 mutate(Ttsum=cumsum(Tt)) 

 df.all <- rbind(df.all,tt.df)

   
}


summary(df.all)
df.all



```

